version: "3.2"
services:
  storm-frontend:
    image: aggarwalnam/storm-frontend:v1
    ports:
      - 8080:80
  storm-backend:
    image: aggarwalnam/storm-backend:v1
    ports:
      - 8055:8055
    depends_on:
      storm-db:
        condition: service_healthy
  storm-db:
    image: mysql:5.7
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - stormdb:/var/lib/mysql
    healthcheck:
      test: "sleep 10"
      interval: 1s
      retries: 120
volumes:
  stormdb: